INSERT INTO films (
	title,
	original_title,
	pegi,
	release_year,
	total_time,
	film_genre,
	average_rating,
	film_description
)
VALUES
('Nadia, butterfly','Nadia, butterfly',0,2021,'1:46:00','Drame',5.00,"Le film fait partie de la Sélection Officielle de Cannes 2020. Nadia, 23 ans, nage pour le Canada aux Jeux olympiques. Cette compétition prestigieuse représente l'aboutissement de sa vie de sacrifices. Pourtant, par peur de rester piégée dans le monde hermétique et éphémère du sport de haut niveau, Nadia a pris la décision..."),
('Nouvel ordre','New Order',12,2021,'1:28:00','Drame',5.00,"Un mariage mondain est interrompu par l'arrivée d'invités importuns."),
('Promising Young Woman','Promising Young Woman',12,2021,'1:54:00','Thriller',5.00,"Tout le monde s'entendait pour dire que Cassie était une jeune femme pleine d'avenir jusqu'à ce qu'un évènement inattendu ne vienne tout bouleverser. Mais rien dans la vie de Cassie n'est en fait conforme aux apparences : elle est aussi intelligente que rusée, séduisante que calculatrice et mêne une double vie dès la nuit..."),
('Tom & Jerry','Tom & Jerry',0,2021,'1:41:00','Animation',5.00,"Les nouvelles aventures de Tom & Jerry dans un long métrage melant CGI et prises de vues réelles. Tom, le chat et Jerry, la souris n'ont plus de domicile. Ils emménagent dans un hôtel chic de New York où Kayla a trouvé un emploi. Mais pour qu'elle puisse le garder, il faut impérativement qu'elle chasse Jerry avant la réception..."),
('Freaky','Freaky',0,2021,'1:42:00','Thriller',5.00,"Millie Kessler, une adolescente de 17 ans, occupée à faire bonne figure dans son très élitiste lycée, Blissfield High, devient la nouvelle cible du Boucher, un tueur en série tristement notoire. Son année de Terminale va alors devenir le cadet de ses soucis. Lorsque, sous l'effet du poignard antique du Boucher ils se réveillent dans le corps de..."),
('9 jours à Raqqa','9 jours à Raqqa',12,2021,'1:30:00','Documentaire',5.00,"Le film fait partie de la Sélection Officielle Cannes 2020. Leïla Mustapha est à 30 ans la nouvelle maire Kurde de Raqqa en Syrie. Ingénieure en génie civil et chargée de la reconstruction de l'ancienne capitale de Daech, elle doit réconcilier la population et arriver à faire vivre la démocratie. La journaliste grand reporter et écrivaine, Marine"),
('Comment je suis devenu super-héros','Comment je suis devenu super-héros',12,2021,'1:37:00','Policier / Espionnage',5.00,"Paris 2020. Dans une société où les surhommes sont banalisés et parfaitement intégrés, une mystérieuse substance procurant des super-pouvoirs à ceux qui n'en ont pas se répand. Face aux incidents qui se multiplient, les lieutenants Moreau et Schaltzmann sont chargés de l'enquête. Avec l'aide de Monté Carlo et Callista, deux..."),
('Fatima','Fatima',12,2021,'1:53:00','Drame',5.00,"Portugal. 1917, trois jeunes bergers de Fatima racontent avoir vu la Vierge Marie. Leurs révélations vont toucher de nombreux croyants mais également attirer la colère des représentants de l'Eglise et du gouvernement. Ils vont tout faire pour essayer d'étouffer l'affaire et obliger les trois enfants à se rétracter. Mais la rumeur..."),
('Mystère à Saint-Tropez','Mystère à Saint-Tropez',12,2021,'','Comédie',5.00,"Aout 1970, en pleine période yéyé. Comme chaque année, le milliardaire Claude Tranchant et sa femme Eliane ont invité le gratin du show-business dans leur somptueuse villa tropézienne. Rien ne semble pouvoir gâcher les festivités, si ce n'est l'inquiétant sabotage de la décapotable du couple. Persuadé d'être victime"),
('Nomadland','Nomadland',12,2021,'1:48:00','Drame',5.00,"Après avoir tout perdu pendant la Grande Récession, une sexagénaire se lance dans un voyage à travers l'Ouest américain, vivant comme un nomade des temps modernes."),
('Nos plus belles années','Nos plus belles années',12,2021,'2:15:00','Comédie dramatique',5.00,"C'est l'histoire de quatre amis, racontée sur quarante ans, en Italie, des années 1980 à aujourd'hui. La chronique de leurs espoirs, de leurs désillusions, de leurs amours, et surtout, de leur amitié."),
('Un homme en colère','Un homme en colère',12,2021,'','Action',5.00,"Un convoyeur de fond fraichement engagé surprend ses collègues par l'incroyable précision de ses tirs de riposte alors qu'ils subissent les assauts de braqueurs expérimentés.Tous se demandent désormais qui il est, d'où il vient et pourquoi est-il là."),
('Délicieux','Délicieux',12,2021,'1:53:00','Comédie dramatique',5.00,"XVIIIe siècle. Un cuisinier est limogé par son maître. Il trouve le courage au contact d'une jeune femme étonnante de se libérer de sa condition de domestique et de proposer son savoir-faire directement au public en créant le premier restaurant."),
("L'un des notres","L'un des notres",12,2021,'1:55:00','Thriller',5.00,"Après la perte de leur fils, le shérif à la retraite George Blackledge et son épouse, Margaret quittent leur ranch du Montana pour sauver leur jeune petit-fils des griffes d'une dangereuse famille tenue d'une main de fer par la matriarche Blanche Weboy. Quand ils découvrent que les Weboy n'ont pas l'intention de laisser partir l'enfant..."),
('Ca tourne à Saint-Pierre et Miquelon','Ca tourne à Saint-Pierre et Miquelon',12,2021,'1:35:00','Comédie dramatique',5.00,"Céline, une actrice, engagée par le célèbre réalisateur Milan Zodowski, arrive à Saint-Pierre et Miquelon. Sur place, il n'y a qu'un ingénieur du son et une régisseuse pour toute équipe et Milan refuse obstinément de sortir du cabanon où il s'est enfermé. Le grand " menteur en sc�ne ", adepte du cinéma vérité, fera-t-il tourner Céline ou l'a-t-il..."),


